# Generated by Django 3.1.7 on 2021-03-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taker', '0002_auto_20210319_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='taker',
            name='showAnwers',
            field=models.BooleanField(null=True),
        ),
    ]
