# Generated by Django 3.1.7 on 2021-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='creator',
            new_name='maker',
        ),
        migrations.AddField(
            model_name='quiz',
            name='timeLimit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
