# Generated by Django 3.1.7 on 2021-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210318_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='startDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
